#!/usr/bin/env python3
"""Generate D1 seed SQL for the coordination Worker.

A Worker has no local files, so the target list (and any preassigned prefix
list) must live in D1. This emits SQL on stdout that you apply with:

    python3 worker/tools/make_seed_sql.py --targets targets.txt \
        [--prefixes prefixes.txt] > seed.sql
    npx wrangler d1 execute keyhunt-coord --file seed.sql --remote

Targets are fully replaced (DELETE then INSERT in file order) and the cached
targets_digest / targets_count in `meta` are refreshed to match exactly what the
Worker would compute. Prefixes are appended as 'pending' blocks, in file order,
to be handed out before any random prefix -- run the prefixes seed only once, or
it will add duplicate pending rows (blocks are not deduplicated by prefix).
"""
import argparse
import hashlib
import sys

PREFIX_HEX_LEN = 54


def sqlstr(s):
    return "'" + s.replace("'", "''") + "'"


def load_pubs(path):
    out = []
    with open(path) as f:
        for line in f:
            s = line.strip().lower()
            if not s or s.startswith("#"):
                continue
            # accept bare compressed/uncompressed; store compressed form as-is
            out.append(s)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--targets", required=True, help="one compressed pubkey per line")
    ap.add_argument("--prefixes", help="optional 54-hex prefixes, one per line")
    ap.add_argument("--space-prefix", default="", help="validate prefixes start with this")
    a = ap.parse_args()

    targets = load_pubs(a.targets)
    digest = hashlib.sha256("\n".join(targets).encode()).hexdigest()

    print("-- keyhunt-coord D1 seed (generated by make_seed_sql.py)")
    print("BEGIN TRANSACTION;")
    print("DELETE FROM targets;")
    for i, pub in enumerate(targets):
        print("INSERT INTO targets(ord, pub) VALUES (%d, %s);" % (i, sqlstr(pub)))
    print("INSERT OR REPLACE INTO meta(k, v) VALUES ('targets_digest', %s);" % sqlstr(digest))
    print("INSERT OR REPLACE INTO meta(k, v) VALUES ('targets_count', %s);" % sqlstr(str(len(targets))))

    if a.prefixes:
        sp = a.space_prefix.lower()
        added = bad = 0
        seen = set()
        for line in open(a.prefixes):
            s = line.strip().lower()
            if not s or s.startswith("#"):
                continue
            if len(s) != PREFIX_HEX_LEN or s in seen:
                bad += 1
                continue
            try:
                int(s, 16)
            except ValueError:
                bad += 1
                continue
            if sp and not s.startswith(sp):
                bad += 1
                continue
            seen.add(s)
            print("INSERT INTO blocks(prefix, state, attempts) VALUES (%s, 'pending', 0);" % sqlstr(s))
            added += 1
        sys.stderr.write("prefixes: %d added, %d skipped\n" % (added, bad))

    print("COMMIT;")
    sys.stderr.write("targets: %d  digest %s\n" % (len(targets), digest[:16]))


if __name__ == "__main__":
    main()
